config/routes.rb
Rails.application.routes.draw do
  resources :orders, only: [:index, :show, :new, :create]
  resources :cakes, only: [:index, :show]
  resources :users, only: [:show, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cake.rb
class Cake < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :cake

  def order_date_str
    self.order_date.strftime("%B %e, %Y at %l:%M %P")
  end

  def fulfilled_str
    self.fulfilled ? "Yes" : "No"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :cakes, through: :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cakes_controller.rb
class CakesController < ApplicationController
  def index
    @cakes = Cake.all
  end

  def show
    @cake = Cake.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all.sort_by { |o| o.user.name }
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(user_id: params[:order][:user], cake_id: params[:order][:cake],
      order_date: DateTime.now, fulfilled: false)

    if @order.valid?
      binding.pry
      @order.save
      redirect_to order_path(@order)
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email))

    if @user.valid?
      @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cakes_helper.rb
module CakesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cakes/index.html.erb
<h1>Available Cakes</h1>
<ul>
<% @cakes.each do |c| %>
  <li><%= link_to c.name, cake_path(c) %></li>
<% end %>
</ul>

app/views/cakes/show.html.erb
<h1><%= @cake.name %></h1>
<p>Flavor Profile: <%= @cake.flavor %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBakery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>
  <%= f.label :user, "User:" %>
  <%= f.collection_select :user, User.all, :id, :name %>
  <%= f.label :cake, "Cake:" %>
  <%= f.collection_select :cake, Cake.all, :id, :name %>
  <%= f.submit "Place Order" %>
<% end %>

app/views/orders/index.html.erb
<h1>All Orders</h1>
<table style="text-align: left; width: 100%">
  <thead>
    <tr>
      <th>Order ID</th>
      <th>User</th>
      <th>Cake</th>
      <th>Order Date</th>
      <th>Fulfilled</th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |o| %>
    <tr>
      <td><%= link_to o.id, order_path(o) %></td>
      <td><%= o.user.name %></td>
      <td><%= o.cake.name %></td>
      <td><%= o.order_date_str %></td>
      <td><%= o.fulfilled_str %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render "form" %>

app/views/orders/show.html.erb
<h1>Order Details</h1>
<table style="text-align: left; width: 100%">
  <thead>
    <tr>
      <th>Order ID</th>
      <th>User</th>
      <th>Cake</th>
      <th>Order Date</th>
      <th>Fulfilled</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @order.id %></td>
      <td><%= @order.user.name %></td>
      <td><%= @order.cake.name %></td>
      <td><%= @order.order_date_str %></td>
      <td><%= @order.fulfilled_str %></td>
    </tr>
  </tbody>
</table>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.submit %>
<% end %>

app/views/users/_orders.html.erb
<h1><%= "Orders for #{@user.name}" %></h1>
<table style="text-align: left">
  <thead>
    <tr>
      <th>Cake</th>
      <th>Date Ordered</th>
      <th>Fulfilled</th>
    </tr>
  </thead>
  <tbody>
  <% @user.orders.each do |o| %>
    <tr>
    <td><%= o.cake.name %></td>
    <td><%= o.order_date_str %></td>
    <td><%= o.fulfilled_str %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form" %>

app/views/users/show.html.erb
<% if !@user.orders.empty? %>
  <%= render "orders" %>
<% else %>
  <h2><%= "#{@user.name}, Welcome!" %></h2>
  <p>It looks like you haven't placed any orders yet. Let's fix that!</p>
<% end %>
<br>
<%= link_to "Place New Order", new_order_path %>